# List of regular expressions to match fully qualified type names.
#
# For example:
#
#   github\.com/sourcegraph/sourcegraph/internal/codeintel/.*
#
# If this list is empty, all structs are tested.
# Default: []
include_types:
- '.+UploadMatchingOptions'

# Same as above, but for exclusion.
#
# Default: []
exclude_types:
# - '.+/cobra\.Command$'
