[package]
name = "sg-syntax"
version = "0.1.0"
authors = ["TJ DeVries <devries.timothyj@gmail.com>"]
edition = "2021"
license = "MIT"
include = ["src/**/*", "queries/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scip.workspace = true
protobuf.workspace = true
tree-sitter.workspace = true
tree-sitter-highlight = "0.20"

syntect = { git = "https://github.com/sourcegraph/syntect" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.0"
base64 = "0.13.0"
anyhow = "1"
libloading = "0.7"
paste = "1.0.6"
once_cell = "1.13.0"

scip-semantic = { git = "https://github.com/sourcegraph/scip-semantic" }
scip-treesitter-languages = { path = "../scip-treesitter-languages" }

[dev-dependencies]
insta = "1.11.0"
pretty_assertions = "1.2.1"
