---
queue: aspect-default
tasks:
    # Checks that the branch is current
    branch_freshness:
        # Rebase PR changes on main, to avoid churning the repository cache
        update_strategy: rebase
    # Checks that BUILD file content is up-to-date with sources
    # gazelle:
    # Checks that all tests are passing
    test:
      bazel:
        rcfiles:
            - ".aspect/bazelrc/ci.sourcegraph.bazelrc"
        flags:
          - --noexperimental_reuse_sandbox_directories
          # looks like this is a big de-optimization since Bazel also downloads all test
          # logs even if coverage is disabled
          - --noexperimental_fetch_all_coverage_outputs
      env:
          CI: "true"
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres
          PGSSLMODE: disable
          REDIS_CACHE_ENDPOINT: ":6379"
          GIT_PAGER: ''
          DISPLAY: ":99"
      targets:
          - //...
          - //testing:grpc_backend_integration_test
          - //testing:codeintel_integration_test
