# Sourcegraph quickStart: https://docs.sourcegraph.com/dev/setup/quickstart
# Gitpod config reference: https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - name: sg
    init: |
      (
        set -e

        ./dev/sg/bootstrap.sh -f -p=false
      )
    command: |
      (
        set -e
    
        echo "Run 'sg setup' to setup development environment"
        echo "https://docs.sourcegraph.com/dev/setup/quickstart"
      )
        
