# Sourcegraph quickStart: https://docs.sourcegraph.com/dev/setup/quickstart
# Gitpod config reference: https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - init: |
      (
        set -e

        ./dev/sg/bootstrap.sh -f -p=false
        sg setup --oss --fix
      )
    #init: curl --proto '=https' --tlsv1.2 -sSLf https://install.sg.dev | sh -s -- -f -p=false
    command: gp top
