version: 2
snapshot:
  widths:
    - 1920 # Full-width browser window
  percy-css: |
    .percy-hide,
    .monaco-editor .cursor {
      visibility: hidden !important;
    }
    .percy-inactive-element {
      pointer-events: none !important;
    }
    .percy-display-none {
      display: none !important;
    }
discovery:
  disable-cache: true
percy:
  # Defer uploading snapshots until the very end of the test suite.
  # This allows many snapshots with the same name AND different widths to be merged together.
  # This is useful for flaky client integration tests that can be retried automatically.
  defer-uploads: true
