logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0013
    level: discard
  - code: YN0007
    level: discard
  - code: YN0061
    level: discard

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.8.1/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
