openapi: 3.0.0
info:
  title: Cody Service
  version: 0.0.0
servers:
- url: /
paths:
  /models:
    get:
      operationId: Models_list
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListModelsResponse'
          description: The request has succeeded.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error response.
      summary: "Lists the currently available models, and provides basic information\
        \ about each one such as the owner and availability."
  /models/{modelId}:
    get:
      operationId: Models_retrieveModel
      parameters:
      - explode: false
        in: path
        name: modelId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
          description: The request has succeeded.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error response.
      summary: "Retrieves a model instance, providing basic information about the\
        \ model such as the owner and permissioning."
components:
  schemas:
    Error:
      example:
        code: 6
        message: message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    ListModelsResponse:
      example:
        data:
        - created: 0
          owned_by: owned_by
          id: id
          object: model
        - created: 0
          owned_by: owned_by
          id: id
          object: model
        object: list
      properties:
        object:
          enum:
          - list
          type: string
        data:
          items:
            $ref: '#/components/schemas/Model'
          type: array
      required:
      - data
      - object
      type: object
    Model:
      description: Describes an OpenAI model offering that can be used with the API.
      example:
        created: 0
        owned_by: owned_by
        id: id
        object: model
      properties:
        id:
          description: "The model identifier, which can be referenced in the API endpoints."
          type: string
        object:
          description: "The object type, which is always \"model\"."
          enum:
          - model
          type: string
        created:
          description: The Unix timestamp (in seconds) when the model was created.
          format: int64
          type: integer
        owned_by:
          description: The organization that owns the model.
          type: string
      required:
      - created
      - id
      - object
      - owned_by
      type: object
