steps:
  - group: "Sourcegraph App"
    steps:
      - label: 'Build Sourcegraph Backend App for Linux'
        key: 'build-sourcegraph-app-linux'
        agents: { queue: bazel }
        env:
          PLATFORM: x86_64-unknown-linux-gnu
        command:
          - './enterprise/dev/app/bazel-build.sh'
      - label: 'Bundle with Tauri'
        key: 'build-tauri-sourcegraph-app'
        depends_on:
          - 'build-sourcegraph-app-linux'
        agents: { queue: stateless }
        command:
          - './dev/ci/pnpm-install-with-retry.sh'
          - './enterprise/dev/app/tauri-build.sh'
          - './enterprise/dev/app/github-release.sh'
        env:
          AWS_CONFIG_FILE: /buildkite/.aws/config
          AWS_SHARED_CREDENTIALS_FILE: /buildkite/.aws/credentials
        plugins:
        - https://github.com/sourcegraph/cache-buildkite-plugin.git#master:
            backend: s3
            id: node_modules_pnpm
            key: cache-node_modules-pnpm-{{ checksum 'pnpm-lock.yaml' }}
            paths:
            - node_modules
            restore_keys:
            - cache-node_modules-pnpm-{{ checksum 'pnpm-lock.yaml' }}
            s3:
              bucket: sourcegraph_buildkite_cache
              endpoint: https://storage.googleapis.com
              profile: buildkite
              region: us-central1
            tarball: {}
