# pipeline.yml sets up the appropriate pipeline to run for any given commit through the
# pipeline generator (see steps).
#
# 🚨 SECURITY: DO NOT DEFINE SECRETS HERE IN PIPELINE ENV - instead, go to
# https://sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/buildkite/kubernetes/gsm-secrets.tf
#
# MUST_INCLUDE_COMMIT, as well as other non-secret variables, are now defined in
# https://sourcegraph.com/github.com/sourcegraph/infrastructure/-/blob/buildkite/kubernetes/buildkite-agent/buildkite-agent.Deployment.yaml

# steps:
#   - group: ":aspect: Aspect Workflows "
#     steps:
#       - key: aspect-workflows-upload
#         if: build.env("DISABLE_ASPECT_WORKFLOWS") != "true"
#         label: ":aspect: Setup Aspect Workflows"
#         commands: |
#           rosetta steps | buildkite-agent pipeline upload
#         agents:
#           queue: aspect-small
#       - label: ":pipeline: Generate pipeline"
#         commands:
#           - "./dev/ci/gen-pipeline.sh"
#         agents:
#           queue: aspect-default

steps:
  - label: ":cheese: running changelog tool in CI"
    agents:
      queue: aspect-small
    command: |
      set -eu -o pipefail

      DEVX_GH_TOKEN="$(gcloud secrets versions access latest --secret=DEVX_SERVICE_GH_TOKEN --quiet --project=sourcegraph-ci)"
      echo $$DEVX_GH_TOKEN | md5sum

      # Find the asset id for the changelog binary on sourcegraph/devx-service latest release
      asset_id=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $$DEVX_GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/sourcegraph/devx-service/releases/latest | jq '.assets[] | select(.name=="changelog") | .id')

      echo "--- found asset id: $$asset_id"

      # Download the binary
      curl -L \
        -H "Accept: application/octet-stream" \
        -H "Authorization: Bearer $$DEVX_GH_TOKEN"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -o changelog \
        "https://api.github.com/repos/sourcegraph/devx-service/releases/assets/$${asset_id}"

      chmod +x changelog

      ./changelog \
        --github.token="$$DEVX_GH_TOKEN" \
        update-as-pr \
        --github.repo="sourcegraph/sourcegraph" \
        --output.repo="sourcegraph/docs" \
        --output.repo.base="main" \
        --output.changelog="docs/CHANGELOG.mdx" \
        --output.changelog.marker='{/* CHANGELOG_START */}' \
        --releaseregistry.token="$$RELEASE_REGISTRY_TOKEN" \
        --releaseregistry.name="sourcegraph" \
        --releaseregistry.version=v5.4.2198
