name: 'Report failure if action failed'
description: 'Creates an error event and sends it to Sentry'
inputs:
  dsn:
    description: "The Sentry DSN to use for error reporting."
    required: true
    type: string
  repo:
    description: "The repository that the failed workflow run belonged to."
    required: true
    type: string
  branch:
    description: "The branch on which the workflow run failed."
    required: true
    type: string
  workflow_name:
    description: "The name of the workflow that failed."
    required: true
    type: string
  job_name:
    description: "The name of the job that failed."
    required: true
    type: string
  run_id:
    description: "The run ID of the failed workflow run."
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
    - name: Send Sentry event for failed action
      if: ${{ failure() }}
      run: |
        npm i -g @sentry/cli
        sentry-cli send-event -m "The Job '${{ inputs.job_name }} in the ${{ inputs.workflow_name }} action has failed - see run for exact failure" \
          -t "github-action:${{ inputs.workflow_name }}" \
          -t "branch:${{ inputs.branch }}" \
          -t "repository:${{ inputs.repo }}" \
          -t "workflow-run: https://github.com/${{ inputs.repo }}/actions/runs/${{ inputs.run_id }}" \
          --no-environ
      env:
        SENTRY_DSN: ${{ inputs.dsn }}
        SENTRY_ORG: sourcegraph
        SENTRY_PROJECT: dev-infra
