[package]
name = "syntect_server"
version = "1.0.1"
authors = [
    "TJ DeVries <devries.timothyj@gmail.com>",
    "Stephen Gutekanst <stephen.gutekanst@gmail.com>"
]
edition = "2018"
license = "MIT"

[dependencies]
syntect = { git = "https://github.com/sourcegraph/syntect" }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustyline = "9.1.2"

sg-syntax = { path = "./crates/sg-syntax" }

scip.workspace = true

[workspace]
members = [
    "crates/sg-syntax",

    # later, these will be pulled out to a separate repo
    "crates/scip-macros",
    # "crates/scip-syntax",
    # "crates/scip-treesitter",
    "crates/scip-treesitter-languages",
    # "crates/ctags",
]

[workspace.dependencies]
scip = { git = "https://github.com/sourcegraph/scip" }

tree-sitter = "0.20.9"
protobuf = "3"
