# Melange-based replacement for https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/gitserver/p4-fusion-install-alpine.sh

package:
  name: p4-fusion-sg
  version: 1.14.0
  epoch: 0
  description: "A fast Perforce to Git conversion tool, Sourcegraph fork"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: 'Copyright (c) 2022 Salesforce, Inc.'
      license: 'BSD 3-Clause License'
  dependencies:
    runtime:
      - libstdc++

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - wget
      - perl
      - bash
      - cmake
      - busybox
      - ca-certificates-bundle

pipeline:
  # Download p4-fusion
  - uses: fetch
    with:
      uri: https://github.com/sourcegraph/p4-fusion/archive/00c54b37be9cbf3b1b70a79fef55ce0e78945c06.tar.gz
      expected-sha256: 6f4fc7726537d934070af3d09b883de843e44ca0496952a1872af46e7449dbab
      extract: false
  - runs: |
      mkdir p4-fusion-src
      tar -C p4-fusion-src -xzf 00c54b37be9cbf3b1b70a79fef55ce0e78945c06.tar.gz --strip 1

  # Download OpenSSL
  - uses: fetch
    with:
      uri: https://www.openssl.org/source/openssl-1.1.1w.tar.gz
      expected-sha256: cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8
      extract: false
  - runs: |
      mkdir openssl-src
      tar -C openssl-src -xzf openssl-1.1.1w.tar.gz --strip 1

  # Download Helix Core C++ API
  - uses: fetch
    with:
      uri: https://filehost.perforce.com/perforce/r23.1/bin.linux26x86_64/p4api-glibc2.3-openssl1.1.1.tgz
      # Hash occasionally changes, available at https://filehost.perforce.com/perforce/r23.1/bin.linux26x86_64/SHA256SUMS (check version)
      expected-sha256: 5243d70b3a34ada544f87b0907d30d5dcd2f2881c0120e6da8dcdf6767a91bc6 # based on url
      extract: false
  - runs: |
      mkdir -p p4-fusion-src/vendor/helix-core-api/linux
      tar -C p4-fusion-src/vendor/helix-core-api/linux -xzf p4api-glibc2.3-openssl1.1.1.tgz --strip 1

  # Build OpenSSL
  - runs: |
      cd openssl-src
      ./config -no-shared
  - runs: |
      cd openssl-src
      make --jobs="$(($(nproc) + 1))"
  - runs: |
      cd openssl-src
      make install

  # Build p4-fusion
  - runs: |
      cd p4-fusion-src
      ./generate_cache.sh RelWithDebInfo
      ./build.sh

  # Copy p4-fusion binary
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local/bin/
      cp p4-fusion-src/build/p4-fusion/p4-fusion ${{targets.destdir}}/usr/local/bin/p4-fusion

update:
  enabled: false # Our p4-fusion fork does not provide releases or tags
