package:
  name: p4cli
  version: 23.1
  epoch: 1
  description: "Command line interface for Perforce"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: 'Copyright (c) 1995-2021, Perforce Software, Inc.'
      license: 'BSD-2-Clause'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://cdist2.perforce.com/perforce/r${{package.version}}/bin.linux26x86_64/p4
      # Hash occasionally changes, available at https://filehost.perforce.com/perforce/r23.1/bin.linux26x86_64/SHA256SUMS (check version)
      expected-sha256: eb258396d0b565cea621e0a123a6ad8886da42ea05bc84664bba4bed08ddee89
      extract: false
  - runs: |
      chmod +x p4
      mkdir -p ${{targets.destdir}}/usr/local/bin/
      cp p4 ${{targets.destdir}}/usr/local/bin/p4
