---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-ui
  labels:
    app: operator-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-ui
  template:
    metadata:
      labels:
        app: operator-ui
    spec:
      containers:
        - name: operator-ui
          image: {{ .Values.registry }}/{{ .Values.webui.image }}
          ports:
            - containerPort: 80
          env:
            - name: API_ENDPOINT
              value: 'http://operator-api.{{ .Release.Namespace }}.svc.cluster.local'
