# Export traces to a Jaeger instance.
#
# Variables:
#
# - $JAEGER_HOST
# - $JAEGER_OTLP_GRPC_PORT

receivers:
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318

exporters:
  otlp/jaeger:
    # Default Jaeger GRPC server
    endpoint: "${JAEGER_HOST}:${JAEGER_OTLP_GRPC_PORT}"
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: ":13133"
  zpages:
    endpoint: ":55679"

service:
  telemetry:
    metrics:
      address: ":8888"
  extensions: [health_check,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
