name: Cody Review

on:
  pull_request:
    types: [labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'cody-review' }}

    steps:
      - name: Leave a comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Hi, I'm Cody! I'm starting my review of this PR. I'll leave comments as I go along.

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check out repository and install
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7.28.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT\

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Cody Review
        run: pnpm --filter ./client/cody-review run review
