# See dev/pr-auditor/README.md
name: pr-auditor
on:
  pull_request:
    types: [ closed, edited ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: { go-version: '1.17' }

      - run: ./dev/pr-auditor/check-pr.sh
        env:
          GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
