on:
  pull_request_target:
    types: [opened]

jobs:
  print-instructions:
    name: "Comment with PR instructions"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:bulb: Learn more about each section: [PR description tips](https://www.notion.so/sourcegraph/Write-a-good-pull-request-description-610a7fd3e613496eb76f450db5a49b6e), [Test Plan](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles) and [Changelog](https://www.notion.so/sourcegraph/Writing-a-changelog-entry-dd997f411d524caabf0d8d38a24a878c).`,
            })
