name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, closed]

  schedule:
    # At minute 0 past every 12th hour
    - cron: '0 */12 * * *'

  # For testing
  push:
    branches:
      - contractors/SG-33486

jobs:
  remove-pr-preview-app:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Delete PR preview app
        if: github.event.action == 'closed'
        run: ./dev/ci/render-pr-preview.sh -d
        env:
          RENDER_COM_API_KEY: ${{ secrets.RENDER_COM_API_KEY }}
          RENDER_COM_OWNER_ID: ${{ secrets.RENDER_COM_OWNER_ID }}
          BUILDKITE_PULL_REQUEST_REPO: "https://github.com/${{ github.repository }}"
          BUILDKITE_BRANCH: ${{ github.head_ref }}

  clean-up-inactive-pr-preview-apps:
    if: github.event_name == 'schedule' || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Clean up inactive PR preview apps
        run: ./dev/ci/render-pr-preview-cleanup.sh -e 5 # 5 days from the last update
        env:
          RENDER_COM_API_KEY: ${{ secrets.RENDER_COM_API_KEY }}
          RENDER_COM_OWNER_ID: ${{ secrets.RENDER_COM_OWNER_ID }}
