name: Release protector
on:
  pull_request:
    types:
      [
        closed,
        edited,
        opened,
        synchronize,
        ready_for_review,
        labeled,
        unlabeled,
      ]
    branches:
      # only run on branches targeting the `main` branch.
      - main

jobs:
  protect-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check date and labels
        id: check-date-and-labels
        run: |
          # Does this PR have the acknowledgement label?
          has_label="${{contains(github.event.pull_request.labels.*.name, 'i-acknowledge-this-goes-into-the-release')}}"

          # Pass the value of the above check into the shell script
          ./.github/workflows/release_protector.sh $has_label
