name: scip-go
on:
  push:
    paths:
      - '**.go'
      - '**/scip-go.yml'

jobs:
  scip-go:
    # Skip running on forks
    if: github.repository == 'sourcegraph/sourcegraph'
    runs-on: ubuntu-latest
    container: sourcegraph/scip-go
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set directory to safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Get src-cli
        run: |
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o /usr/local/bin/src
          chmod +x /usr/local/bin/src

      - name: Run scip-go
        shell: bash
        run: |
          ROOT_DIRS=('.' 'lib' 'monitoring' 'enterprise/dev/ci/images')
          for ROOT_DIR in "${ROOT_DIRS[@]}"
          do
            pushd "$ROOT_DIR"
            scip-go --no-animation
            ENDPOINTS=('https://sourcegraph.com/' 'https://sourcegraph.sourcegraph.com/' 'https://demo.sourcegraph.com/')
            for ENDPOINT in "${ENDPOINTS[@]}"
            do
              SRC_ENDPOINT="$ENDPOINT" src code-intel upload -github-token='${{ secrets.GITHUB_TOKEN }}' -no-progress -repo=github.com/sourcegraph/sourcegraph
            done
            popd
          done
