name: sg-binary-release

on:
  push:
    branches:
      - main
      - mrn/testing-sg-cross-compiling
    paths:
      - 'dev/sg/**'
      - '.github/workflows/sg-binary-release.yml'

env:
  GOFLAGS: -trimpath
  CGO_ENABLED: '1'

jobs:
  create_release:
    name: create-github-release
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.release.outputs.release_name }}
    steps:
      - name: create-github-release
        id: release
        run: |
          today=$(date +'%Y-%m-%d-%H-%M')
          short_sha=$(echo ${{ github.sha }} | cut -c1-8)

          # # ATTENTION: release_name is a duplicate from the last step in this
          # # file, because I can't get workflow outputs to work. If you change
          # # one, make sure you change the other.
          # release_name="THORSTEN-TESTING"

          # echo "### sg snapshot release" >> /tmp/release-notes.md
          # echo "" >> /tmp/release-notes.md
          # echo "Commit: https://github.com/sourcegraph/sourcegraph/commit/${{github.sha}}" >> /tmp/release-notes.md

          # gh release delete -R="${repo}" ${release_name} || true
          # gh release create -R="${repo}" ${release_name} --notes-file /tmp/release-notes.md

          # echo "::set-output name=release_name::${release_name}"
        env:
          repo: sourcegraph/sg
          # GITHUB_TOKEN: ${{ secrets.SG_RELEASE_TOKEN }}

  build:
    name: build
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=path::$(go env GOPATH)"
          echo "::set-output name=exe::$(go env GOEXE)"
          echo "::set-output name=hostos::$(go env GOHOSTOS)"
          echo "::set-output name=hostarch::$(go env GOHOSTARCH)"
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"

      - name: Get asset name
        id: asset
        run: echo "::set-output name=filename::sg_${GOOS}_${GOARCH}${GOEXE}"
        env:
          GOEXE: ${{ steps.go-env.outputs.exe }}

      - name: Build release asset for macOS
        if: startsWith(matrix.os, 'macos-') == true
        run: |
          cd dev/sg
          export CGO_ENABLED=1
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          go install -trimpath -ldflags "-s -w -X main.BuildCommit=$(git rev-list -1 HEAD .)" .

      - name: Build release asset for Linux
        if: startsWith(matrix.os, 'ubuntu-') == true
        run: |
          cd dev/sg
          export CGO_ENABLED=1
          go install -trimpath -ldflags "-s -w -X main.BuildCommit=$(git rev-list -1 HEAD .)" .

      - name: Move asset to GOPATH/bin
        if: ${{ steps.go-env.outputs.hostos != matrix.os || steps.go-env.outputs.hostarch != matrix.arch }}
        working-directory: ${{ steps.go-env.outputs.path }}/bin/${{ matrix.os }}_${{ matrix.arch }}
        run: mv sg"${GOEXE}" ..
        env:
          GOEXE: ${{ steps.go-env.outputs.exe }}

      - name: Move asset to workspace
        working-directory: ${{ steps.go-env.outputs.path }}/bin
        run: mv sg"${GOEXE}" "${workspace}"/"${filename}"
        env:
          GOEXE: ${{ steps.go-env.outputs.exe }}
          workspace: ${{ github.workspace }}
          filename: ${{ steps.asset.outputs.filename }}

      - name: Upload release asset
        run: |
          release_name="${{ needs.create_release.outputs.release_name }}"

          echo "filename=${filename}"
          # gh release upload -R="${repo}" ${release_name} "${filename}"
        env:
          repo: sourcegraph/sg
          filename: ${{ steps.asset.outputs.filename }}
          # GITHUB_TOKEN: ${{ secrets.SG_RELEASE_TOKEN }}
