name: team-label
on:
   pull_request:
     types: [opened, reopened]
jobs:
  team-labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: buf-breaking-action@a074e988ee34efcd4927079e79c611f428354c01 # SECURITY: pin third-party action hashes
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
