name: Tracking Issue Syncer
on:
  schedule:
  - cron: '*/15 * * * *'
  issues:
    types:
    - opened
    - edited
    - deleted
    - closed
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - milestoned
    - demilestoned
  pull_request:
    types:
    - opened
    - edited
    - closed
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
permissions:
  contents: read

jobs:
  sync-tracking-issues:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - uses: docker://sourcegraph/tracking-issue:latest
        env:
          GITHUB_TOKEN: ${{ secrets.TRACKING_ISSUE_SYNCER_TOKEN }}
