name: TruffleHog Secrets Scan
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.0

      - name: Install TruffleHog
        run: |
          go install github.com/trufflesecurity/trufflehog@latest

      - name: Run TruffleHog
        id: scan
        run: |
          output=$(~/go/bin/trufflehog git file://./ --since-commit main --branch HEAD --no-update --github-actions --only-verified)
          echo ::set-output name=secrets::$(echo "$output" | grep -q "Found verified"; echo $?)

      - name: Post to Slack
        if: ${{ steps.scan.outputs.secrets == '0' }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "🚨 *A secret was detected in a GitHub commit in the repo ${{ github.repository }}.*\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚨 *A secret was detected in a GitHub commit in the repo ${{ github.repository }}.*\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TRUFFLEHOG_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
