name: 'wolfictl-update'

on:
  push:
  # schedule:
    # everyday at 0:00 UTC
    # - cron:  0 0 * * *
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  wolfictl-update:
    name: Wolfictl Update
    runs-on: ubuntu-latest

    steps:
      - uses: wolfi-dev/actions/install-wolfictl@main

      - name: List
        run: |
          which wolfictl


      - name: List2
        run: |
          wolfictl version

      - name: "wolfictl update"
        run: |
          wolfictl update --dry-run --create-issues false --package-name qdrant --path wolfi-packages/ --github-labels SSDLC --github-labels wolfi-auto-update $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
